/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    projects: Project;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'site-content': SiteContent;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles?: ('admin' | 'editor')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Texte alternatif court et descriptif pour le SEO et l'accessibilite.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * Use 'home' for the homepage.
   */
  slug: string;
  published?: boolean | null;
  /**
   * Add, remove and drag sections to change the page structure.
   */
  layout: (
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeHero';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeClientLogos';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeCommandCenter';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeServices';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeProcess';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeApproach';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeTestimonials';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeStats';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeCollaborationGuides';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homePricing';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeTechStack';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeProjects';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeVisitorTracking';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeFAQ';
      }
    | {
        /**
         * Optional label shown to editors only.
         */
        adminLabel?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeCTAFinal';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * Stable FR/EN pairing key. Do not change after publishing.
   */
  key: string;
  slug: string;
  isLanding?: boolean | null;
  sortOrder?: number | null;
  published?: boolean | null;
  /**
   * Material Symbols icon name, e.g. automation or code_blocks.
   */
  icon: string;
  color: 'indigo' | 'emerald' | 'blue' | 'purple' | 'sky' | 'amber';
  title: string;
  description: string;
  cardTitle?: string | null;
  cardDescription?: string | null;
  /**
   * Structured landing content migrated from the current site. Keep JSON valid; later we can replace this with marketer-friendly blocks.
   */
  landing?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  slug: string;
  subtitle: string;
  description: string;
  category: 'webapp' | 'workflow' | 'site-metier';
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Image geree par Payload pour les nouveaux contenus.
   */
  media?: (string | null) | Media;
  /**
   * Chemin public existant, conserve pour la migration et les fallbacks.
   */
  image: string;
  imageAlt?: string | null;
  link?: string | null;
  workflowFile?: string | null;
  role?: string | null;
  results?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  /**
   * Compatibilite avec l'ancien schema Supabase. La publication Payload reste la source principale.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  /**
   * Markdown conserve pour le rendu public actuel.
   */
  content: string;
  coverMedia?: (string | null) | Media;
  coverImage?: string | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  author: string;
  readingTime: number;
  seoTitle?: string | null;
  seoDescription?: string | null;
  publishedAt?: string | null;
  /**
   * Compatibilite avec l'ancien schema Supabase. La publication Payload reste la source principale.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  published?: T;
  layout?:
    | T
    | {
        homeHero?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeClientLogos?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeCommandCenter?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeServices?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeProcess?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeApproach?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeTestimonials?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeStats?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeCollaborationGuides?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homePricing?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeTechStack?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeProjects?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeVisitorTracking?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeFAQ?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
        homeCTAFinal?:
          | T
          | {
              adminLabel?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  key?: T;
  slug?: T;
  isLanding?: T;
  sortOrder?: T;
  published?: T;
  icon?: T;
  color?: T;
  title?: T;
  description?: T;
  cardTitle?: T;
  cardDescription?: T;
  landing?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  description?: T;
  category?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  media?: T;
  image?: T;
  imageAlt?: T;
  link?: T;
  workflowFile?: T;
  role?: T;
  results?:
    | T
    | {
        item?: T;
        id?: T;
      };
  featured?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  coverMedia?: T;
  coverImage?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  author?: T;
  readingTime?: T;
  seoTitle?: T;
  seoDescription?: T;
  publishedAt?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  identity?: {
    name?: string | null;
    headline?: string | null;
    bio?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    location?: string | null;
    availability?: string | null;
  };
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    ogImage?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: string;
  /**
   * Full localized site dictionary migrated from the codebase. Keep valid JSON; use the dedicated collections for services, projects and posts.
   */
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  identity?:
    | T
    | {
        name?: T;
        headline?: T;
        bio?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        location?: T;
        availability?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        ogImage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  content?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}